cyclotion/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index_handler

urlpatterns = [
    path('admin/', admin.site.urls),
    path('routes/', include('routecycling.urls', namespace='route')),
    path('', include('shopproduct.urls', namespace='product')),
    path('articles/', include('article.urls', namespace='article')),
    path('', include('main.urls', namespace='main')),
    path('', include('dummy.urls', namespace='dummy')),
    path('', index_handler, name='index'),
    path('', include('write_bike_shop_review.urls', namespace='write_bike_shop_review')),
]

main/urls.py
from django.urls import path
import main.views as views

app_name = 'main'

urlpatterns = [
    path('login/', views.login_handler, name='login'),
    path('logout/', views.logout_handler, name='logout'),
    path('register/', views.register_handler, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

shopproduct/urls.py
from django.urls import path
import shopproduct.views as views

from django.conf.urls.static import static
from django.conf import settings

app_name = 'product'

urlpatterns = [
    path('shops/', views.shoplist_handler, name='shop-list'),
    path('shops/search/', views.shoplistsearch_handler, name='shop-search'),

    path('shops/me', views.productlist_private_handler, name='product-private'),
    path('shop/<int:shopid>/products', views.productlist_public_handler, name='product-public'),

    path('products/add', views.productadd_handler, name='product-add'),
    path('products/<int:productid>/edit', views.productedit_handler, name='product-edit'),
    path('products/<int:productid>/delete', views.productdelete_handler, name='product-delete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

write_bike_shop_review/urls.py
from django.urls import path
import write_bike_shop_review.views as views

app_name = 'write_bike_shop_review'

urlpatterns = [
    path('shop/<int:shopid>/reviews/', views.read_review_handler, name='read_review'),
    path('shop/<int:shopid>/reviews/add', views.create_review_handler, name='create_review'),
    path('shop/<int:shopid>/review/<int:reviewid>/edit', views.update_review_handler, name='update_review'),
    path('shop/<int:shopid>/review/<int:reviewid>/delete', views.delete_review_handler, name='delete_review'),
]

templates/shops/list.html
{% extends '../base.html' %}
{% load static %}
{% block title %}{{ title }} | {% endblock %}

{% block customcss %}
<style>
  .shop-board:hover {
    cursor: pointer;
  }

  .shop-board:hover .card-body {
    background-color: #7700ff !important;
    color: white !important;
  }

  .shop-board .card-body {
    height: 110px;
    overflow: hidden;
  }

  .shop-desc {
    height: 50px;
    overflow: clip;
  }
</style>
{% endblock %}

{% block content %}
<div class="container mt-5">
  <h1 class="fw-bold h2 mb-4">{{ title }}</h1>
  <div class="container mt-3">
    <div class="row">
      <form action="{% url 'product:shop-search' %}">
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="Search shop..." aria-describedby="button-addon2" name="query">
          <div class="input-group-append">
            <button class="btn btn-primary" type="submit" id="button-addon2">Search</button>
          </div>
        </div>
      </form>
    </div>
    <div class="row">
      {% for bikeShop in bikeShops %}
      <div class="col-md-3"><div data-href="{% url 'product:product-public' shopid=bikeShop.id %}" class="card mb-4 shadow-sm shop-board">
        <img src="https://avatars.dicebear.com/api/identicon/shop-id1.svg" width="100%">
        <div class="card-body">
          <h4 class="card-text">{{ bikeShop.user.first_name }}</h4>
          <medium class="shop-desc">{{ bikeShop.description|truncatechars:24 }}</medium><br>
          <small>{{ bikeShop.address|truncatechars:25 }}</small>
        </div>
      </div></div>
      {% endfor %}
    </div>
  </div>
  {% include '../pagination.html' %}
</div>
{% endblock %}

{% block customjs %}
<script>
  $('.shop-board').click(function(){
    let url = $(this).data('href')
    location.href = url
  })
</script>
{% endblock %}

templates/shops/view.html
{% extends '../base.html' %}
{% load static %}
{% block title %}{{ shop.user.first_name }} | {% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col">
      <div class="my-2 p-4 bg-body rounded shadow-sm d-flex justified-content-center">
        <img class="bd-placeholder-img flex-shrink-0 me-2 rounded my-auto" width="125" height="125" src="https://avatars.dicebear.com/api/identicon/idartikel2.svg"></img>
        <div class="mx-3 w-100">   
          <h6 class="pb-2 mb-0 h2 fw-bold">{{ shop.user.first_name }}</h6>
          <small>{{ shop.address }}</small>
          <p>{{ shop.description }}</p>
          <hr>
          <div class="d-flex my-2">
            <h6 class="my-auto me-2">Products: <a href="{% url 'product:product-public' shopid=shopid %}">{{ shopitem.count }} products</a></h6>
          </div>
          <div class="d-flex my-2">
            <h6 class="my-auto me-2">
              Reviews:
              <a href="{% url 'write_bike_shop_review:read_review' shopid=shopid %}">{{ reviewcount }} reviews</a>
            </h6>
            <a class="btn btn-sm btn-warning" href="{% url 'write_bike_shop_review:create_review' shopid=shopid %}"><strong>add review</strong></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% block subcontent %}{% endblock %}
{% endblock %}