article/urls.py
from django.urls import path
import article.views as views

app_name = 'article'

urlpatterns = [
    path('', views.articlelist_public_handler, name='article-public'),
    path('me', views.articlelist_private_handler, name='article-private'),
    path('add', views.articleadd_handler, name='article-add'),
    path('article/<int:articleid>', views.articleview_handler, name='article-view'),
    path('article/<int:articleid>/edit', views.articleedit_handler, name='article-edit'),
    path('article/<int:articleid>/delete', views.articledelete_handler, name='article-delete'),
    path('article/<int:articleid>/comment/add', views.addcomment_handler, name='article-commentadd'),
    path('article/<int:articleid>/comment/<int:commentid>/delete', views.deletecomment_handler, name='article-commentdelete'),
    path('article/<int:articleid>/vote', views.vote_handler, name='vote-handler'),
]

cyclotion/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index_handler

urlpatterns = [
    path('admin/', admin.site.urls),
    path('routes/', include('routecycling.urls', namespace='route')),
    path('', include('shopproduct.urls', namespace='product')),
    path('articles/', include('article.urls', namespace='article')),
    path('', include('main.urls', namespace='main')),
    path('', include('dummy.urls', namespace='dummy')),
    path('', index_handler, name='index'),
    path('', include('write_bike_shop_review.urls', namespace='write_bike_shop_review')),
]

main/urls.py
from django.urls import path
import main.views as views

app_name = 'main'

urlpatterns = [
    path('login/', views.login_handler, name='login'),
    path('logout/', views.logout_handler, name='logout'),
    path('register/', views.register_handler, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

article/models.py
from django.db import models

from django.contrib.auth.models import User

class Article(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(null=False, max_length=200)
    content = models.TextField(null=False)
    dateCreated = models.DateTimeField(auto_now_add=True)

class VoteArticle(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    value = models.FloatField()

    class Meta:
        unique_together = ('user', 'article', )
        
class ArticleComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    comment = models.TextField()

article/forms.py
from django import forms
from django.db.models import fields

from article.models import Article, ArticleComment

class CreateArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ("title", "content", "user")

class CreateArticleCommentForm(forms.ModelForm):
    class Meta:
        model = ArticleComment
        fields = ("comment", "user", "article")
    

article/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, Paginator
from django.http import QueryDict
from django.shortcuts import render, redirect

from article.forms import CreateArticleCommentForm, CreateArticleForm
from article.models import Article, ArticleComment, VoteArticle

def get_paginator(request, obj):
    numPage = request.GET.get('page', '1')
    if not numPage.isdigit():
        numPage = 1
    numPage = int(numPage)
    try:
        objPage = Paginator(obj, 25).page(numPage)
        obj = objPage.object_list
    except EmptyPage:
        obj = []
    return {
        'objects': obj,
        'page': [numPage - 1, numPage, numPage + 1]
    }


@login_required(login_url='main:login')
def articlelist_public_handler(req):
    obj = Article.objects.all()
    return render(req, "articles/public.html", context=get_paginator(req, obj))

@login_required(login_url='main:login')
def articlelist_private_handler(req):
    obj = Article.objects.filter(user = req.user)
    return render(req, "articles/private.html", context=get_paginator(req, obj))

@login_required(login_url='main:login')
def articleadd_handler(req):
    articleForm = CreateArticleForm()
    if req.method == 'POST':
        postBody = req.POST.copy()
        postBody['user'] = req.user.pk
        articleForm = CreateArticleForm(data=postBody)
        if articleForm.is_valid():
            articleForm.save()
            messages.success(req, "Article has been added successfully")
            return redirect('article:article-private')
    return render(req, "articles/add.html", {'form': articleForm})

@login_required(login_url='main:login')
def articleedit_handler(req, articleid):
    article = Article.objects.get(id = articleid)
    if article.user.pk != req.user.pk:
        messages.error(req, "You do not have permission to edit this article!")
        return redirect('article:article-private')
    articleForm = CreateArticleForm()
    context = {'article': article, 'form': articleForm}
    if req.method == 'POST':
        postBody = req.POST.copy()
        postBody['user'] = req.user.pk
        articleForm = CreateArticleForm(data=postBody)
        if articleForm.is_valid():
            article.title = postBody['title']
            article.content = postBody['content']
            article.save()
            messages.success(req, "Article has been updated successfully")
            return redirect('article:article-private')
    return render(req, "articles/edit.html",context=context)

@login_required(login_url='main:login')
def articledelete_handler(req, articleid):
    article = Article.objects.get(id = articleid)
    if req.user == article.user:
        article.delete()
        messages.success(req, "Article has been deleted sucessfully")
    else:
        messages.error(req, "You do not have permission to delete this article!")
    return redirect('article:article-private')

@login_required(login_url='main:login')
def articleview_handler(req, articleid):
    article = Article.objects.get(id = articleid)
    comments = ArticleComment.objects.filter(article = article)
    commentsCount = comments.count()
    context = {'article': article, 'comments': comments, 'commentsCount': commentsCount, 'rating': get_vote(article, req.user)}
    return render(req, "articles/view.html", context=context)

@login_required(login_url='main:login')
def addcomment_handler(req, articleid):
    if req.method == 'POST':
        postBody = req.POST.copy()
        postBody['user'] = req.user.pk
        postBody['article'] = Article.objects.get(id=articleid)
        commentForm = CreateArticleCommentForm(data=postBody)
        if commentForm.is_valid():
            commentForm.save()
            messages.success(req, "Comment has been added successfully")
            return redirect('article:article-view', articleid=articleid)

@login_required(login_url='main:login')
def deletecomment_handler(req, articleid, commentid):
    toBeDeleted = ArticleComment.objects.get(id=commentid)
    if req.user == toBeDeleted.user:
        toBeDeleted.delete()
        messages.success(req, "Comment has been deleted successfully")
    else:
        messages.error(req, "You do not have permission to delete this comment!")
    return redirect('article:article-view', articleid=articleid)

def get_vote(article, user):
    allRating = 0
    userVote = None
    try:        
        votes = VoteArticle.objects.filter(article=article)
        for vote in votes:
            allRating += vote.value
        allRating /= votes.count()

        userVote = VoteArticle.objects.get(article=article, user=user)
        userVote = userVote.value
    except:
        pass

    return {
        'all': allRating,
        'user': userVote
    }

@login_required(login_url='main:login')
def vote_handler(req, articleid):    
    try:
        if req.method == 'POST':
            if req.POST.get("rating") == None:
                raise ValueError
            rating = max(int(req.POST.get("rating")), 1)
 
        article = Article.objects.get(id=articleid)
        vote = VoteArticle.objects.get(article=article, user=req.user)
        if req.method == 'POST':
            vote.value = rating
            vote.save()
        else:
            vote.delete()
    except ValueError:
        pass
    except:
        if article != None and req.method == 'POST':
            vote = VoteArticle(article=article, user=req.user, value=rating)
            vote.save()
    return redirect('article:article-view', articleid=articleid)

templates/articles/add.html
{% extends '../base.html' %}
{% load static %}
{% block title %}Add Article | {% endblock %}

{% block customcss %}
<style>
  .ck-editor__editable_inline {
    min-height: 400px;
  }
</style>
{% endblock %}

{% block content %}
<div class="container mt-5">
  <h1 class="fw-bold h2 mb-3">Add Article</h1>
  <div class="container">
    <div class="row justified-content-center">
      <div class="col mx-auto my-3 p-3 bg-body rounded shadow-sm">
        <form class="mt-3" method="post">
          {% csrf_token %}
          <div class="mb-3">
            <label for="id_title" class="form-label">Title</label>
            <textarea style="resize: none" class="form-control" id="id_title" name="title" placeholder="Enter your article title" rows="2" maxlength="200" required></textarea>
          </div>
          <div class="mb-3">
            <label for="id_content" class="form-label">Content</label>
            <textarea class="form-control" id="id_content" name="content" rows="10" required></textarea>
          </div>
          <div class="float-end">
            <a href="{% url 'article:article-private' %}" class="btn btn-secondary">Cancel</a>
            <button type="submit" class="btn btn-primary">Publish</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block customjs %}
{% endblock %}

templates/articles/delete.html
<div id="delete-article-modal" class="modal" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Do you want to delete it?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Once you delete the article, all the comments and rating will be delete automatically too.</p>
        <p>The article you want to delete is <code id="delete-article-label"></code></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
        <a type="button" class="btn btn-secondary" id="delete-article-btn" href="">Yes, delete now</a>
      </div>
    </div>
  </div>
</div>

templates/articles/edit.html
{% extends '../base.html' %}
{% load static %}
{% block title %}Edit Article | {% endblock %}

{% block customcss %}
<style>
  .ck-editor__editable_inline {
    min-height: 400px;
  }
</style>
{% endblock %}

{% block content %}
<div class="container mt-5">
  <h1 class="fw-bold h2 mb-3">Edit Article</h1>
  <div class="container">
    <div class="row justified-content-center">
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
          {{message}}
        </div>
      {% endfor %}
  
      <div class="col mx-auto my-3 p-3 bg-body rounded shadow-sm">
        <form class="mt-3" method="post">
          {% csrf_token %}
          <div class="mb-3">
            <label for="id_title" class="form-label">Title</label>
            <textarea style="resize: none" class="form-control" id="id_title" name="title" rows="2" maxlength="200" required>{{article.title}}</textarea>
          </div>
          <div class="mb-3">
            <label for="id_content" class="form-label">Content</label>
            <textarea class="form-control" id="id_content" name="content" rows="10" required>{{article.content}}</textarea>
          </div>
          <div class="float-end">
            <a href="{% url 'article:article-private' %}" class="btn btn-secondary">Cancel</a>
            <button type="submit" class="btn btn-primary">Publish</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block customjs %}
{% endblock %}

templates/articles/private.html
{% extends '../base.html' %}
{% load static %}
{% block title %}My Article | {% endblock %}

{% block content %}
<div class="container mt-5">
  <h1 class="fw-bold h2 mb-4">
    <span class="mx-auto">My Article</span>
    <a href="{% url 'article:article-add' %}" class="btn btn-primary">Add</a>
  </h1>
  <div class="container mt-3">
    {% for obj in objects %}
    <div class="row">
      <div class="col">
        <div class="p-4 bg-body rounded shadow-sm d-flex justified-content-center">
          <img class="bd-placeholder-img flex-shrink-0 me-2 rounded my-auto" width="125" height="125" src="https://avatars.dicebear.com/api/identicon/idartikel/{{ obj.id }}.svg"></img>
          <div class="mx-3">   
            <h6 class="my-2 pb-2 mb-0 h4 fw-bold article-title">{{ obj.title }}</h6>
            <p>{{ obj.content }}</p>
            <button data-href="{% url 'article:article-delete' articleid=obj.id %}" class="btn btn-danger btn-delete-article" data-bs-toggle="modal" data-bs-target="#delete-article-modal">Delete</button>
            <a class="btn btn-warning" href="{% url 'article:article-edit' articleid=obj.id %}">Edit</a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% include '../pagination.html' %}
</div>
{% include './delete.html' %}
{% endblock %}

{% block customjs %}
<script>
  $('.btn-delete-article').click(function(){
    let url = $(this).attr("data-href")
    let title = $(this).siblings('.article-title').html()
    $('#delete-article-label').html(title)
    $('#delete-article-btn').attr("href", url)
  })
</script>
<script>
  $(document).ready(() => {
    {% for msg in messages %}
    if("{{ msg.tags }}" == "success"){
      swal({
        title: "{{ msg }}",
        icon: "success",
      });
    } else {
      swal({
        title: "{{ msg }}",
        icon: "error",
      });
    }
    {% endfor %}
  })
</script>
{% endblock %}

templates/articles/public.html
{% extends '../base.html' %}
{% load static %}
{% block title %}Article | {% endblock %}

{% block content %}
<div class="container mt-5">
  <h1 class="fw-bold h2 mb-4">Article</h1>
  <div class="container mt-3">
    {% for obj in objects %}
    <div class="row">
      <div class="col">
        <div class="p-4 bg-body rounded shadow-sm d-flex justified-content-center">
          <img class="bd-placeholder-img flex-shrink-0 me-2 rounded my-auto" width="125" height="125" src="https://avatars.dicebear.com/api/identicon/idartikel/{{ obj.id }}.svg"></img>
          <div class="mx-3">   
            <h6 class="my-2 pb-2 mb-0 h4 fw-bold">{{ obj.title }}</h6>
            <p>{{ obj.content }}</p>
            <a class="btn btn-primary" href="{% url 'article:article-view' articleid=obj.id %}">Read more</a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% include '../pagination.html' %}
</div>
{% endblock %}

templates/articles/view.html
{% extends '../base.html' %}
{% load static %}
{% block title %}{{article.title}} | {% endblock %}

{% block customcss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/rating-star.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-5">
  <h1 class="fw-bold h2 mb-4">{{article.title}}</h1>
  <div class="container mt-3">
    <div class="p-4 bg-body rounded shadow-sm">
      <p style="white-space: pre-wrap;">{{article.content}}</p>
      <hr>
      <div class="d-flex">
        <span class="d-flex mb-2">
          <h6 class="my-auto me-2">Your rating:</h6>
          <div class="article-rating me-2"></div>
          <h6 id="user-rating" class="my-auto ms-3 mx-2">{{ rating.user|default:'-' }}/10</h6>
        </span>
        {% if rating.user %}
        <a class="btn btn-sm btn-danger mb-2" href="{% url 'article:vote-handler' articleid=article.id %}"><strong>delete</strong></a>
        {% endif %}
      </div>
      <div class="d-flex my-2">
        <h6 class="my-auto me-2">Ratings: <strong>{{ rating.all|default:0 }}</strong>/10</h6>
      </div>
      <div class="d-flex my-2">
        <h6 class="my-auto me-2">Comments: {{ commentsCount }}</h6>
        <button class="btn btn-sm btn-warning" id="btn-add-comment"><strong>add</strong></button>
      </div>
    </div>
  </div>
</div>
{% include './comments/list.html' %}
{% include './comments/add.html' %}
{% include './comments/success.html' %}
{% include './comments/fail.html' %}
{% endblock %}

{% block customjs %}
<script src="{% static 'js/rating-star.min.js' %}"></script>
<script>
  let addCommentModal = new bootstrap.Modal($('#add-comment-modal'))

  let newComment = $('#new-comment')
  let deleteBtn = $('#delete-btn')

  $(document).ready(function() {
    newComment.hide()
  })

  // https://nashio.github.io/star-rating-svg/demo/
  let lastUserRating = {{ rating.user|default:0 }}
  $(".article-rating").starRating({
      starSize: 20,
      initialRating: {{ rating.user|default:0 }} / 2,
      callback: function(currentRating, $el){
        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
        $.post("{% url 'article:vote-handler' articleid=article.id %}", {
          rating: currentRating * 2,
          csrfmiddlewaretoken: csrftoken
        }, () => {
          location.reload()
        })
      },
      onHover: function(currentIndex, currentRating, $el){
			  $("#user-rating").html(currentIndex * 2 + "/10")
      },
      onLeave: function(currentIndex, currentRating, $el){
        if (lastUserRating == 0) {
          $("#user-rating").html("-/10")
        } else {
          $("#user-rating").html(lastUserRating + "/10")
        }
      }
  });
  $("#btn-add-comment").click(() => {
    addCommentModal.show()
  })
</script>
<script>
  $(document).ready(() => {
    {% for msg in messages %}
    if("{{ msg.tags }}" == "success"){
      swal({
        title: "{{ msg }}",
        icon: "success",
      });
    } else {
      swal({
        title: "{{ msg }}",
        icon: "error",
      });
    }
    {% endfor %}
  })
</script>
{% endblock %}