article/urls.py
from django.urls import path
import article.views as views

app_name = 'article'

urlpatterns = [
    path('', views.articlelist_public_handler, name='article-public'),
    path('me', views.articlelist_private_handler, name='article-private'),
    path('add', views.articleadd_handler, name='article-add'),
    path('article/<int:articleid>', views.articleview_handler, name='article-view'),
    path('article/<int:articleid>/edit', views.articleedit_handler, name='article-edit'),
    path('article/<int:articleid>/delete', views.articledelete_handler, name='article-delete'),
    path('article/<int:articleid>/comment/add', views.addcomment_handler, name='article-commentadd'),
    path('article/<int:articleid>/comment/<int:commentid>/delete', views.deletecomment_handler, name='article-commentdelete'),
    path('article/<int:articleid>/vote', views.vote_handler, name='vote-handler'),
]

cyclotion/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index_handler

urlpatterns = [
    path('admin/', admin.site.urls),
    path('routes/', include('routecycling.urls', namespace='route')),
    path('', include('shopproduct.urls', namespace='product')),
    path('articles/', include('article.urls', namespace='article')),
    path('', include('main.urls', namespace='main')),
    path('', include('dummy.urls', namespace='dummy')),
    path('', index_handler, name='index'),
    path('', include('write_bike_shop_review.urls', namespace='write_bike_shop_review')),
]

main/urls.py
from django.urls import path
import main.views as views

app_name = 'main'

urlpatterns = [
    path('login/', views.login_handler, name='login'),
    path('logout/', views.logout_handler, name='logout'),
    path('register/', views.register_handler, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

routecycling/urls.py
from django.urls import path
import routecycling.views as views

app_name = 'route'

urlpatterns = [
    path('', views.routelist_public_handler, name='route-public'),
    path('me', views.routelist_private_handler, name='route-private'),
    path('add', views.routeadd_handler, name='route-add'),
]

shopproduct/urls.py
from django.urls import path
import shopproduct.views as views

from django.conf.urls.static import static
from django.conf import settings

app_name = 'product'

urlpatterns = [
    path('shops/', views.shoplist_handler, name='shop-list'),
    path('shops/search/', views.shoplistsearch_handler, name='shop-search'),

    path('shops/me', views.productlist_private_handler, name='product-private'),
    path('shop/<int:shopid>/products', views.productlist_public_handler, name='product-public'),

    path('products/add', views.productadd_handler, name='product-add'),
    path('products/<int:productid>/edit', views.productedit_handler, name='product-edit'),
    path('products/<int:productid>/delete', views.productdelete_handler, name='product-delete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<title>{% block title %}{% endblock %}Cyclotion</title>
	
	<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/custom.css' %}">
	
	{% block customcss %}{% endblock %}
</head>
<body class="bg-light" style="font-family: Nunito;">
	{% include 'navbar.html' %}
	<main>
		{% block content %}{% endblock %}
	</main>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
	{% block customjs %}{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <div class="p-3 mb-4 rounded-3">
    <div class="container-fluid py-5">
      <h1 class="display-5 fw-bold">Mudahnya Bersepeda</h1>
      <p class="col-md-8 fs-4">Dapatkan banyak tips menarik bersepeda yang tidak Anda temukan di tempat lain. Lalu, rancang perjalanan sepeda Anda demi mendapatkan pengalaman lebih. Tak lupa, lengkapi kebutuhan sepeda Anda!</p>
      <a class="btn btn-primary btn-lg fw-bold" href="{% url 'main:register' %}">
        Join now!
      </a>
    </div>
  </div>
</div>
{% endblock %}

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light fw-bold" style="background: transparent;">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">
      <img height="30px" src="{% static 'image/cyclotion-logo.png' %}">
      Cyclotion
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarToggler">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:dashboard' %}">Dashboard</a>
        </li>
        {% if request.session.bikeshop %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'product:product-private' %}">My Shop</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'product:shop-list' %}">Browse Shop</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Article
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'article:article-public' %}">All</a></li>
            <li><a class="dropdown-item" href="{% url 'article:article-private' %}">My Article</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Route
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'route:route-public' %}">All</a></li>
            <li><a class="dropdown-item" href="{% url 'route:route-private' %}">My Route</a></li>
          </ul>
        </li>
        {% endif %}
      </ul>
      <ul class="navbar-nav mb-2 mb-lg-0">
        {% if user.is_authenticated %}
          <li class="nav-item me-1 mb-1">
            <a class="btn btn-outline-primary" href="{% url 'main:logout' %}">Logout</a>
          </li>
        {% else %}
        <li class="nav-item me-1">
          <a class="btn btn-primary" href="{% url 'main:login' %}">Login</a>
        </li>
          <li class="nav-item me-1 mb-1">
            <a class="btn btn-outline-primary" href="{% url 'main:register' %}">Register</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/notification.html
{% block id %}{% endblock %}
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{% block notifications %}{% endblock %}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="h1 text-center mt-2 mb-2" style="font-size: 100px !important;">
            {% block symbol %}{% endblock %}
            <!-- {% if notificationIsSuccessful %}
                <span style="color: green;">✔</span>
            {% elif not notificationIsSuccesful %}
                <span style="color: red;">✘</span>
            {% endif %} -->
        </div>
      </div>
    </div>
  </div>
</div>

templates/pagination.html
<div class="d-flex justify-content-center align-items-center mt-3">
  <nav>
    <ul class="pagination">
      {% if page.0 > 0 %}
      <li class="page-item"><a class="page-link" href="?page={{ page.0 }}">&lt;</a></li>
      {% endif %}
      <li class="page-item active"><a class="page-link">{{ page.1|default:'1' }}</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ page.2 }}">&gt;</a></li>
    </ul>
  </nav>
</div>