cyclotion/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index_handler

urlpatterns = [
    path('admin/', admin.site.urls),
    path('routes/', include('routecycling.urls', namespace='route')),
    path('', include('shopproduct.urls', namespace='product')),
    path('articles/', include('article.urls', namespace='article')),
    path('', include('main.urls', namespace='main')),
    path('', include('dummy.urls', namespace='dummy')),
    path('', index_handler, name='index'),
    path('', include('write_bike_shop_review.urls', namespace='write_bike_shop_review')),
]

main/urls.py
from django.urls import path
import main.views as views

app_name = 'main'

urlpatterns = [
    path('login/', views.login_handler, name='login'),
    path('logout/', views.logout_handler, name='logout'),
    path('register/', views.register_handler, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

write_bike_shop_review/urls.py
from django.urls import path
import write_bike_shop_review.views as views

app_name = 'write_bike_shop_review'

urlpatterns = [
    path('shop/<int:shopid>/reviews/', views.read_review_handler, name='read_review'),
    path('shop/<int:shopid>/reviews/add', views.create_review_handler, name='create_review'),
    path('shop/<int:shopid>/review/<int:reviewid>/edit', views.update_review_handler, name='update_review'),
    path('shop/<int:shopid>/review/<int:reviewid>/delete', views.delete_review_handler, name='delete_review'),
]

templates/shops/reviews/add.html
{% extends '../../base.html' %}
{% load static %}
{% block title %}Add Review | {% endblock %}

{% block content %}
<div class="container mt-5">
  <h1 class="fw-bold h2 mb-3">Add Review - Nama Shop</h1>
  <div class="container">
    <div class="row justified-content-center">
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
          {{message}}
        </div>
      {% endfor %}
  
      <div class="col mx-auto my-3 p-3 bg-body rounded shadow-sm">
        <form action="{% url 'write_bike_shop_review:create_review' shopid=shopid %}" class="mt-3" method="post">
          {% csrf_token %}
          <div class="mb-3">
            <label for="inpReview" class="form-label">Your review</label>
            <textarea class="form-control" id="inpReview" name="content" rows="3" required></textarea>
          </div>
          <div class="float-end">
            <a href="{% url 'write_bike_shop_review:read_review' shopid=shopid %}" class="btn btn-secondary">Cancel</a>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block customjs %}
{% endblock %}

templates/shops/reviews/delete.html
<div id="delete-review-modal" class="modal" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-body">
        <p>Are you sure want to delete your review?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
        <a type="button" class="btn btn-secondary" id="delete-review-btn" href="">Yes, delete now</a>
      </div>
    </div>
  </div>
</div>

templates/shops/reviews/edit.html
{% extends '../../base.html' %}
{% load static %}
{% block title %}Edit Review | {% endblock %}

{% block content %}
<div class="container mt-5">
  <h1 class="fw-bold h2 mb-3">Edit Review - Nama Shop</h1>
  <div class="container">
    <div class="row justified-content-center">
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
          {{message}}
        </div>
      {% endfor %}
  
      <div class="col mx-auto my-3 p-3 bg-body rounded shadow-sm">
        <form action="{% url 'write_bike_shop_review:update_review' shopid=shopid reviewid=review.id %}" class="mt-3" method="post">
          {% csrf_token %}
          <div class="mb-3">
            <label for="inpReview" class="form-label">Your review</label>
            <textarea class="form-control" id="inpReview" name="content" rows="3" required">{{ review.content }}</textarea>
          </div>
          <div class="float-end">
            <a href="{% url 'write_bike_shop_review:read_review' shopid=shopid %}" class="btn btn-secondary">Cancel</a>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block customjs %}
{% endblock %}

templates/shops/reviews/list.html
{% extends '../view.html' %}
{% load static %}
{% block title %}Nama Shop | {% endblock %}

{% block subcontent %}
<div class="container my-5">
  <h1 class="fw-bold h2 mb-4">Reviews</h1>
  <div class="container mt-3">
    {% for review in reviews %}
      <div class="row">
        <div class="col">
          <div class="p-4 bg-body rounded shadow-sm d-flex justified-content-center">
            <img class="bd-placeholder-img flex-shrink-0 me-2 rounded my-auto" width="50" height="50" src="https://avatars.dicebear.com/api/identicon/{{ review.user }}.svg"></img>
            <div class="mx-3">
              {% if review.user == user %}
                <div class="float-end">
                  <a class="btn btn-sm btn-warning" href="{% url 'write_bike_shop_review:update_review' shopid=shopid reviewid=review.id %}">Edit</a>
                  <a data-href="{% url 'write_bike_shop_review:delete_review' shopid=shopid reviewid=review.id %}" class="btn btn-sm btn-danger btn-delete-review" data-bs-toggle="modal" data-bs-target="#delete-review-modal">
                    Delete
                  </a>
                </div>
              {% endif %}
              <h6 class="my-2 pb-2 mb-0 h5 fw-bold">
                <span>{{ review.user.first_name }}</span>
              </h6>
              <p>{{ review.content }}</p>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% include './delete.html' %}
{% endblock %}

{% block customjs %}
<script>
  $('.btn-delete-review').click(function(){
    let url = $(this).attr("data-href")
    $('#delete-review-btn').attr("href", url)
  })
</script>
<script>
  $(document).ready(() => {
    {% for msg in messages %}
    if("{{ msg.tags }}" == "success"){
      swal({
        title: "{{ msg }}",
        icon: "success",
      });
    } else {
      swal({
        title: "{{ msg }}",
        icon: "error",
      });
    }
    {% endfor %}
  })
</script>
{% endblock %}